@startuml "Caso de uso - Synviewer"
actor "Usuário" as User


package Synviewer {
   
    
    (Acessar página inicial) --> (Selecionar "Synviewer")
  package ParsersTycho{
    rectangle Executar_parser{
      (Selecionar aba "Executar o parser") --> (Inserir sentença)
      (Inserir sentença) --> (Selecionar modelo parser)
      (Selecionar modelo parser) --> (Executar parser)
    }

    rectangle Exibir_Árvore_Sintática{
      (Selecionar aba "Exibir Árvore Sintática") --> (Inserir expressão)
      (Inserir expressão) --> (Executar)
    }

    rectangle Exibir_Formato_Tycho{
      (Selecionar aba "Exibir Formato Tycho") --> (Inserir dados)
      (Inserir dados) --> (Executar_)
    }
  }

  package DependênciasUniversais {
    (Inserir sentença ou expressão CoNLL-U) --> (Selecionar o modelo de parser)
    (Selecionar o modelo de parser) --> (_Executar)

  }

  (Selecionar "Synviewer") --> ParsersTycho
  (Selecionar "Synviewer") --> DependênciasUniversais
}




User -- Synviewer:  https://www.tycho.iel.unicamp.br/home


note bottom of (Inserir expressão)
  É possível realizar conversão de notação (parênteses x colchetes)
end note

note bottom of DependênciasUniversais
  O usuário pode visualizar e exportar 
  árvores no formato CoNLL-U ou Dependências Universais.
  É possível inserir a expressão em CoNLL-U para geração das árvores diretamente.
end note
@enduml


