@startuml Caso de uso 07-Ferramenta de Pesquisa
actor "Usuário" as User

package Pesquisa {

    (Acessar página inicial) --> (Acessar Ferramenta "Search")
    (Acessar Ferramenta "Search") --> (Selecionar corpus)
    package PesquisaSimples {
        (Selecionar "Pesquisa Simples") -->(Preencher regex)
        
        
    }

    (Selecionar corpus) --> (PesquisaSimples)
   
    package PesquisaSintatica {
        rectangle ModoSintatico1 {
        (Selecionar parâmetros \n de pesquisa \n para os colocados) 

    }
        rectangle ModoSintatico2 {
            (Selecionar "escreva \n sua pesquisa")--> (Clicar "Converter texto")
        }
        (Selecionar "Pesquisa Sintática") --> ModoSintatico1
        (Selecionar "Pesquisa Sintática") --> ModoSintatico2
    }
    (Selecionar corpus) --> (PesquisaSintatica)
    PesquisaSimples --> (Executar Pesquisa)
    PesquisaSintatica --> (Executar Pesquisa)
    }

User -- Pesquisa 

note top of (Acessar página inicial)
https://www.tycho.iel.unicamp.br/home
endnote

@enduml
