@startuml "Caso de uso 00"

actor "Usuário/Adminstrador" as User 


rectangle AcessoPerfil {
    (Acessar home) --> (Acessar "Área reservada")
    (Acessar "Área reservada") --> (Realizar login)
    (Realizar login) -->  (Acesso ao perfil)
}

User -- (Acessar home): https://www.tycho.iel.unicamp.br/home
User -- (Acessar "Área reservada")
User -- (Realizar login)