@startuml "Caso de uso 04.01 Criação corpus"
actor "Usuário" as User

package CriaçãoCorpora {
   
    
    (Acessar página inicial) --> (Selecionar Ferramenta Corpus Management)

    (Selecionar Ferramenta Corpus Management) --> (Acessar + Create new corpus)

   (Acessar + Create new corpus) --> (Adicionar nome ao novo corpus) 
}


note left of User
  Pré-requisitos:
  1. Usuário cadastrado com e-mail Google (.gmail)
  2. Usuário logado no perfil Google
end note

note right of (Adicionar nome ao novo corpus)
Clicar em "confirmar"
end note

User -- (Acessar página inicial):  https://www.tycho.iel.unicamp.br/home
User -- (Selecionar Ferramenta Corpus Management)
User --  (Acessar + Create new corpus)
@enduml