@startuml "Caso de uso 5.01 - Edição dos corpora"

actor "Usuário/Admin" as User 

package EdiçãoCorpora {
         (Acessar página inicial)-->(Selecionar Ferramenta eDictor)
         (Selecionar Ferramenta eDictor)-->(Selecionar corpus)
         (Selecionar corpus)->(Acessar "Exibir informações")
         (Acessar "Exibir informações")-->(Selecionar o "eDictor Translations")
         (Selecionar o "eDictor Translations")-->(Selecionar par de sentenças)
         package InserirSentenças{
            (Selecionar "Inserir texto")-->(Clicar em "Sincronizar")

         }
         package EditarSentSincronizadas {
            
            (Selecionar botão E-eDictor)-->(Editar sentença original)
            (Selecionar botão E-eDictor)-->(Editar sentença traduzida)
         }
         
         package RemoverSincronizadas{
            (Clicar em "Remover" e confirmar)
         }

         (Selecionar o "eDictor Translations")->InserirSentenças
         (Selecionar par de sentenças)-->(Selecionar "Apagar")
         (Selecionar par de sentenças)-->EditarSentSincronizadas
         (Selecionar par de sentenças)-->RemoverSincronizadas



note top of (Selecionar "Apagar")
Textos já sincronizados são mantidos
end note
}

note right of  (Selecionar "Inserir texto")
Inserir o texto fonte (original);
selecionar o idioma de tradução; 
inserir texto traduzido e salvar as alterações
end note

note right of (Clicar em "Sincronizar")
Sentenças fonte e alvo 
são apresentados paralelamente
end note

User -- (Acessar página inicial)
User -- (Selecionar Ferramenta eDictor)
User -- (Selecionar corpus)
User -- (Acessar "Exibir informações")
User -- (Selecionar o "eDictor Translations")
User -- (Selecionar par de sentenças)
User -- InserirSentenças
User -- EditarSentSincronizadas
User -- RemoverSincronizadas
@enduml



