@startuml "Caso de uso 6.01 - Edição dos corpora"

actor "Usuário/Admin" as User 
 User -- UseEDictorAções
package UseEDictorAções {
          
        ("+Adicionar novo documento" e Preencher) --> (Selecionar eDictor)
        (Selecionar eDictor) --> (Upload imagem)
        (Upload imagem) --> Transcrição
        Transcrição --> OperaçõesEdição
        
}



rectangle Transcrição{
        (... )
        }

rectangle OperaçõesEdição{
   (...)

}

@enduml




rectangle Transcricao{
        (Transcrição) --> (Manual)
        (Transcrição) --> (Automática)
        (Manual)-->(Clicar o botão "Transcrição")
        (Automática)-->(Clicar o botão "extrair texto de imagem")
        (Clicar o botão "extrair texto de imagem")-->(Clicar ícone de "ir para o modo edição")
        (Clicar o botão "Transcrição")-->(Clicar ícone de "ir para o modo edição")
        }


rectangle Operacoes{
    (Etiquetagem e outras) -->(...)
    (Anotação sintática)-->(...)
    (Revisão etiquetas POS)-->(...)

}