@startuml "Caso de uso 6.01 - Edição dos corpora"

actor "Usuário/Admin" as User 
User -- EdiçãoCorpora_eDictorTranslations
package EdiçãoCorpora_eDictorTranslations  {
         (Acessar página inicial)-->(Selecionar Ferramenta eDictor)
         (Selecionar Ferramenta eDictor)-->(Selecionar corpus)
         (Selecionar corpus)-->(Acessar "Exibir informações")
         (Acessar "Exibir informações")-->(Selecionar o "eDictor Translations")
         
         package AcoesNoCorpus as Acoes{
            
         (...)

        
}
(Selecionar o "eDictor Translations")-->Acoes
 

@enduml



