@startuml "Caso de uso 6.01 - Edição dos corpora"

actor "Usuário/Admin" as User 

package AçõesCorpora {
 
         package EditarSentSincronizadas {
            
            (Selecionar botão E-eDictor)-->(Editar sentença original)
            (Selecionar botão E-eDictor)-->(Editar sentença traduzida)
         }
         
         package RemoverSincronizadas{
            (Clicar em "Remover" e confirmar)
         }
       

         (Selecionar o "eDictor Translations")-->(Selecionar "Inserir texto"):Incluir novas sentenças
         (Selecionar "Inserir texto")-->(Preencher textos):Para inserir
         (Preencher textos)-->(Clicar em "Sincronizar")
         (Selecionar "Inserir texto")-->(Selecionar "Apagar"):Para apagar
         (Selecionar o "eDictor Translations")-->(Selecionar par de sentenças)
         (Selecionar par de sentenças)-->ApagarSentenças
         (Selecionar par de sentenças)-->EditarSentSincronizadas
         (Selecionar par de sentenças)-->RemoverSincronizadas



note top of (Selecionar "Apagar")
Textos já sincronizados são mantidos
end note
}


note left of  (Preencher textos)
Inserir o texto fonte (original);
selecionar o idioma de tradução; 
inserir texto traduzido e salvar as alterações
end note

note bottom of (Clicar em "Sincronizar")
Sentenças fonte e alvo 
são apresentados paralelamente
end note

@enduml



