@startuml "Caso de uso 04.02 Criação corpus"
actor "Usuário/Admin" as User


package ConfiguraçãoCorpora {
   
    
    (Acessar página inicial) --> (Selecionar Ferramenta Corpus Management)

    (Selecionar Ferramenta Corpus Management) --> (Selecionar corpus e aba "Parâmetros")

   (Selecionar corpus e aba "Parâmetros") --> (Realizar configurações)
}


note right of User
  Pré-requisitos:
  1. Usuário cadastrado com e-mail Google (.gmail)
  2. Usuário logado no perfil Google
end note

note right of (Realizar configurações)
Botões de configuração:
1. Public corpus
2. Active
3. Use Morphemes
4. Use Sound
5. Use Translations
6. Use Lexicon
7. Use Grid
8. Use Category
9. Use Edition Tiers
10. Use eDictor Translations
11. Use eDictor
12. Use Designer
13. Use Transcriber
14. Allow POS Tag inclusion
15. Default for UD
end note
/' 
note right of (Adicionar nome ao novo corpus)
Clicar em "confirmar"
end note
 '/
User -- (Acessar página inicial):  https://www.tycho.iel.unicamp.br/home
User -- (Selecionar Ferramenta Corpus Management)
User-- (Selecionar corpus e aba "Parâmetros")
User -- (Realizar configurações)
@enduml