@startuml "Caso de uso 6.01 - Edição dos corpora"

actor "Usuário/Admin" as User 

package EdiçãoCorpora_eDictorTranslations  {
         (Acessar página inicial)-->(Selecionar Ferramenta eDictor)
         (Selecionar Ferramenta eDictor)-->(Selecionar corpus)
         (Selecionar corpus)-->(Acessar "Exibir informações")
         (Acessar "Exibir informações")-->(Selecionar o "eDictor Translations")
         
         package AcoesNoCorpus as Acoes{
            
         (Selecionar o "eDictor Translations")-->(Inserir Sentenças)
         (Selecionar o "eDictor Translations")-->(Apagar Sentenças)
         (Selecionar o "eDictor Translations")--> (Editar Sentenças Sincronizadas)
         (Selecionar o "eDictor Translations")-->(Remover Sentenças Sincronizadas)
}


        
}

 
User -- (Acessar página inicial)
User -- (Selecionar Ferramenta eDictor)
User--(Selecionar corpus)
User--(Acessar "Exibir informações")
User--(Selecionar o "eDictor Translations")
User -- (Acoes)
@enduml



